# Generated by Django 4.1.7 on 2023-04-01 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_pub_date_post_created_on_post_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(help_text='Post unique url', max_length=200, unique=True),
        ),
    ]
