# Generated by Django 4.1.7 on 2023-04-19 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover_image',
            field=models.ImageField(null=True, upload_to='images/post/'),
        ),
    ]
