# Generated by Django 4.1.7 on 2023-04-08 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myusermodel',
            name='gender',
            field=models.CharField(choices=[('n', 'not specified'), ('f', 'female'), ('m', 'male')], default='n', max_length=10),
        ),
    ]
