# Generated by Django 4.1.7 on 2023-04-10 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_myusermodel_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myusermodel',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='myusermodel',
            name='last_name',
        ),
        migrations.AddField(
            model_name='myusermodel',
            name='full_name',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
