# Generated by Django 4.1.7 on 2023-04-19 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_myusermodel_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myusermodel',
            name='pfp',
            field=models.ImageField(null=True, upload_to='images/users/'),
        ),
    ]
