# Generated by Django 4.1.7 on 2023-04-25 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_myusermodel_pfp'),
    ]

    operations = [
        migrations.AddField(
            model_name='myusermodel',
            name='Country',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
